"""
Module 05 — Properties Report
===============================
Generates combined properties report. All reads from run directory.

Usage:
    python3 modules/05_properties/properties_report.py --run-dir path
"""

import argparse
import json
import logging
import sys
from datetime import date
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]


def fmt(val, decimals=1, suffix=""):
    if val is None: return "N/A"
    if isinstance(val, float): return f"{val:.{decimals}f}{suffix}"
    return str(val)


def generate_report(candidates):
    total = len(candidates)
    unstable = sum(1 for c in candidates if c.get("physicochemical", {}).get("is_unstable"))
    high_protease = sum(1 for c in candidates if c.get("protease_cleavage", {}).get("protease_risk") == "high")
    needs_delivery = sum(1 for c in candidates if c.get("permeability", {}).get("overall_permeability") == "needs_delivery_system")

    lines = [
        f"# PeptideScreen — Properties Report",
        f"**Date:** {date.today()} | **Candidates:** {total}",
        "",
        "## Summary",
        f"- Unstable (index > 40): {unstable}/{total}",
        f"- High protease risk: {high_protease}/{total}",
        f"- Needs delivery system: {needs_delivery}/{total}",
        "",
        "## All Candidates",
        "",
        "| ID | Seq | MW | Charge | Stable? | Protease | Permeability |",
        "|----|-----|---:|-------:|---------|----------|-------------|",
    ]

    for c in candidates:
        seq = c["sequence"][:15] + ".." if len(c["sequence"]) > 15 else c["sequence"]
        pc = c.get("physicochemical", {})
        pr = c.get("protease_cleavage", {})
        pm = c.get("permeability", {})

        mw = fmt(pc.get("molecular_weight_da"), 0)
        charge = fmt(pc.get("net_charge_ph74"), 1)
        stable = "yes" if pc and not pc.get("is_unstable") else ("**NO**" if pc else "?")
        prot = pr.get("protease_risk", "?")
        perm = pm.get("mw_category", "?")

        lines.append(f"| {c['id']} | `{seq}` | {mw} | {charge} | {stable} | {prot} | {perm} |")

    lines.append(f"\n---\n*Generated by PeptideScreen Module 05*")
    return "\n".join(lines)


def run(run_dir: str) -> None:
    sys.path.insert(0, str(ROOT))
    from modules.run_manager import RunManager

    rm = RunManager(run_dir=run_dir)
    candidates = rm.load_candidates()

    if not candidates:
        log.error("No candidates found.")
        return

    report = generate_report(candidates)
    report_path = rm.reports_dir / "properties_report.md"
    report_path.write_text(report)
    log.info(f"Properties report → {report_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", required=True)
    args = parser.parse_args()
    run(run_dir=args.run_dir)
