"""
Module 03 — Step 1: HADDOCK3 Docking
=====================================
Docks peptide candidates into the receptor binding pocket using HADDOCK3.
Two modes:

  FAST SCREEN: rigidbody only (all candidates, ~2-3 min each)
  FULL VALIDATION: rigidbody + flexref + emref (top N, ~30-50 min each)

Usage:
    python3 modules/03_docking/haddock3_dock.py --run-dir path --mode fast
    python3 modules/03_docking/haddock3_dock.py --run-dir path --mode full --n 20

Inputs:
    {run_dir}/candidates/candidate_pool.json
    {run_dir}/processed/*_interface.json
    data/candidates/folded_structures/ (peptide PDBs)

Outputs:
    {run_dir}/docking/haddock3/{candidate_id}/ (per-candidate results)
    Updates candidate_pool.json with haddock_score
"""

import argparse
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parents[2]


def extract_receptor_pdb(pdb_path: Path, chain_id: str, output_path: Path) -> Path:
    """Extract receptor chain from PDB, removing water and heterogens."""
    from Bio.PDB import PDBParser, PDBIO, Select

    class ReceptorSelect(Select):
        def accept_chain(self, chain):
            return chain.id == chain_id

        def accept_residue(self, residue):
            return residue.get_id()[0] == " "  # skip heterogens/water

    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(pdb_path.stem, str(pdb_path))

    io = PDBIO()
    io.set_structure(structure)
    io.save(str(output_path), ReceptorSelect())

    return output_path


def generate_air_file(
    active_residues: list[int],
    receptor_chain: str,
    ligand_chain: str,
    output_path: Path,
) -> Path:
    """Generate Ambiguous Interaction Restraints (AIR) file for HADDOCK3."""
    lines = []

    for res_num in active_residues:
        lines.append(
            f"assign (resi {res_num} and segid {receptor_chain})\n"
            f"       (\n"
            f"        (resi * and segid {ligand_chain})\n"
            f"       ) 2.0 2.0 0.0"
        )

    output_path.write_text("\n!\n".join(lines))
    return output_path


def generate_cfg(
    receptor_pdb: Path,
    peptide_pdb: Path,
    air_file: Path,
    run_dir: Path,
    mode: str = "fast",
    sampling: dict = None,
) -> Path:
    """
    Generate HADDOCK3 configuration file.

    mode="fast": rigidbody + caprieval only
    mode="full": rigidbody + seletop + flexref + emref + caprieval
    """
    sampling = sampling or {}

    if mode == "fast":
        rigidbody_n = sampling.get("rigidbody_fast", 50)
        workflow = f"""
[topoaa]

[rigidbody]
ambig_fname = "{air_file}"
sampling = {rigidbody_n}

[caprieval]
"""
    else:  # full
        rigidbody_n = sampling.get("rigidbody", 1000)
        flexref_n = sampling.get("flexref", 200)
        emref_n = sampling.get("emref", 200)
        workflow = f"""
[topoaa]

[rigidbody]
ambig_fname = "{air_file}"
sampling = {rigidbody_n}

[seletop]
select = 200

[flexref]
ambig_fname = "{air_file}"
sampling = {flexref_n}

[emref]
ambig_fname = "{air_file}"
sampling = {emref_n}

[caprieval]
"""

    cfg_content = f"""# HADDOCK3 configuration — {mode} mode
# Auto-generated by PeptideScreen

run_dir = "{run_dir}"

molecules = [
    "{receptor_pdb}",
    "{peptide_pdb}",
]
{workflow}"""

    cfg_path = run_dir.parent / f"{run_dir.name}.cfg"
    cfg_path.write_text(cfg_content)
    return cfg_path


def run_haddock3(cfg_path: Path, timeout: int = 3600) -> bool:
    """Execute HADDOCK3."""
    env = os.environ.copy()
    if not env.get("CNS_SOLVE"):
        cns_path = ROOT / "tools" / "cns_solve"
        if cns_path.exists():
            env["CNS_SOLVE"] = str(cns_path)

    haddock_bin = ROOT / ".venv" / "bin" / "haddock3"
    if not haddock_bin.exists():
        haddock_bin = "haddock3"

    result = subprocess.run(
        [str(haddock_bin), str(cfg_path)],
        capture_output=True,
        text=True,
        timeout=timeout,
        env=env,
    )

    if result.returncode != 0:
        log.error(f"  HADDOCK3 error: {result.stderr[:300]}")
        return False

    return True


def parse_results(run_dir: Path) -> float | None:
    """Parse best HADDOCK score from caprieval output."""
    capri_files = sorted(run_dir.glob("*caprieval*/capri_ss.tsv"))
    if not capri_files:
        # Try alternative output locations
        capri_files = sorted(run_dir.glob("*/capri_ss.tsv"))
    if not capri_files:
        log.warning("  No caprieval results found")
        return None

    capri_file = capri_files[-1]
    best_score = None

    with open(capri_file) as f:
        header = f.readline().strip().split("\t")
        score_idx = None
        for i, col in enumerate(header):
            if col.strip('"') == "score":
                score_idx = i
                break

        if score_idx is None:
            # Try 'total' or first numeric column
            for i, col in enumerate(header):
                if "score" in col.lower() or "total" in col.lower():
                    score_idx = i
                    break

        if score_idx is None:
            log.warning(f"  Could not find score column in {capri_file.name}")
            log.warning(f"  Columns: {header}")
            return None

        for line in f:
            parts = line.strip().split("\t")
            if len(parts) > score_idx:
                try:
                    score = float(parts[score_idx].strip('"'))
                    if best_score is None or score < best_score:
                        best_score = score
                except ValueError:
                    continue

    return best_score


def dock_candidate(
    candidate: dict,
    receptor_pdb: Path,
    interface: dict,
    folded_dir: Path,
    output_dir: Path,
    mode: str = "fast",
    sampling: dict = None,
) -> float | None:
    """
    Dock a single candidate. Returns HADDOCK score or None on failure.
    """
    cid = candidate["id"]

    # Get peptide PDB
    peptide_pdb = folded_dir / f"{cid}.pdb"
    if not peptide_pdb.exists():
        log.warning(f"  No PDB for {cid}")
        return None

    # Set up candidate directory
    cand_dir = output_dir / cid
    cand_dir.mkdir(parents=True, exist_ok=True)

    # Generate AIR restraints
    air_file = cand_dir / "ambig.tbl"
    generate_air_file(
        active_residues=interface["active_residues"],
        receptor_chain=interface["receptor_chain"],
        ligand_chain="A",  # peptide PDB from PeptideBuilder uses chain A
        output_path=air_file,
    )

    # Generate HADDOCK3 config
    h3_run_dir = cand_dir / "run"
    cfg_path = generate_cfg(
        receptor_pdb=receptor_pdb,
        peptide_pdb=peptide_pdb,
        air_file=air_file,
        run_dir=h3_run_dir,
        mode=mode,
        sampling=sampling,
    )

    # Run HADDOCK3
    timeout = 1800 if mode == "fast" else 7200
    success = run_haddock3(cfg_path, timeout=timeout)
    if not success:
        return None

    # Parse score
    score = parse_results(h3_run_dir)
    return score


def run(run_dir: str, mode: str = "fast", n: int = None) -> list[dict]:
    """
    Run HADDOCK3 docking for candidates.

    Args:
        run_dir: path to the run directory
        mode: "fast" (rigidbody only) or "full" (complete refinement)
        n: number of candidates to dock (None = all for fast, top N for full)
    """
    sys.path.insert(0, str(ROOT))
    from modules.run_manager import RunManager

    rm = RunManager(run_dir=run_dir)
    config = rm.config
    candidates = rm.load_candidates()

    haddock_cfg = config.get("docking", {}).get("haddock3", {})
    sampling = haddock_cfg.get("sampling", {})

    # Select candidates to dock
    if mode == "full":
        # Prefer AF2-filtered candidates, fall back to fast screen
        af2_passed = [c for c in candidates if c.get("af2_pass")]
        if af2_passed:
            # Sort by ipTM (best first)
            af2_passed.sort(key=lambda c: c.get("af2_iptm", 0), reverse=True)
            to_dock = af2_passed[:n] if n else af2_passed
            log.info(f"FULL mode: docking {len(to_dock)} AF2-validated candidates")
        else:
            # Fall back to fast screen scores
            scored = [c for c in candidates if c.get("haddock_fast_score") is not None]
            scored.sort(key=lambda c: c["haddock_fast_score"])
            n = n or haddock_cfg.get("max_candidates", 20)
            to_dock = scored[:n]
            log.info(f"FULL mode: docking top {len(to_dock)} by fast screen (no AF2 data)")
    else:
        to_dock = candidates if n is None else candidates[:n]
        log.info(f"FAST mode: screening {len(to_dock)} candidates")

    if not to_dock:
        log.error("No candidates to dock.")
        return candidates

    # Prepare receptor PDB
    target_cfg = config["targets"][0]  # first target
    interface = rm.load_interface(target_cfg["name"])
    pdb_path = rm.structures_dir / f"{interface['pdb_id']}.pdb"

    receptor_dir = rm.docking_dir / "receptor"
    receptor_dir.mkdir(parents=True, exist_ok=True)
    receptor_pdb = receptor_dir / f"{interface['pdb_id']}_receptor.pdb"

    if not receptor_pdb.exists():
        log.info(f"Extracting receptor chain {interface['receptor_chain']}...")
        extract_receptor_pdb(pdb_path, interface["receptor_chain"], receptor_pdb)

    # Folded structures directory
    folded_dir = rm.folded_dir
    if not folded_dir.exists():
        log.error(f"Folded structures not found at {folded_dir}. Run fold_peptides.py first.")
        return candidates

    # Docking output directory
    haddock_dir = rm.docking_dir / f"haddock3_{mode}"
    haddock_dir.mkdir(parents=True, exist_ok=True)

    score_field = "haddock_fast_score" if mode == "fast" else "haddock_full_score"
    scored_count = 0
    failed_count = 0

    for i, candidate in enumerate(to_dock):
        cid = candidate["id"]

        # Skip if already scored in this mode
        if candidate.get(score_field) is not None:
            scored_count += 1
            continue

        log.info(f"\n[{i+1}/{len(to_dock)}] {cid} ({candidate['sequence']})")

        score = dock_candidate(
            candidate=candidate,
            receptor_pdb=receptor_pdb,
            interface=interface,
            folded_dir=folded_dir,
            output_dir=haddock_dir,
            mode=mode,
            sampling=sampling,
        )

        if score is not None:
            # Update in the main candidates list
            for c in candidates:
                if c["id"] == cid:
                    c[score_field] = score
                    break
            scored_count += 1
            log.info(f"  HADDOCK score: {score:.1f}")
        else:
            failed_count += 1
            log.error(f"  Docking failed")

        # Checkpoint every 5 candidates
        if (i + 1) % 5 == 0:
            rm.save_candidates(candidates)
            log.info(f"  Checkpoint ({scored_count} scored, {failed_count} failed)")

    # Final save
    rm.save_candidates(candidates)

    status = f"haddock3_{mode}_complete"
    rm.update_status(status)

    log.info(f"\nHADDOCK3 {mode} docking complete.")
    log.info(f"  Scored: {scored_count}/{len(to_dock)}")
    log.info(f"  Failed: {failed_count}/{len(to_dock)}")

    # Print top 10
    scored_list = [c for c in candidates if c.get(score_field) is not None]
    scored_list.sort(key=lambda c: c[score_field])
    if scored_list:
        log.info(f"\nTop 10 by {score_field}:")
        for rank, c in enumerate(scored_list[:10], 1):
            log.info(f"  {rank}. {c['id']}  {c['sequence']}  score={c[score_field]:.1f}")

    return candidates


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", required=True, help="Run directory")
    parser.add_argument("--mode", choices=["fast", "full"], default="fast", help="Docking mode")
    parser.add_argument("--n", type=int, default=None, help="Number of candidates (full mode)")
    args = parser.parse_args()
    run(run_dir=args.run_dir, mode=args.mode, n=args.n)
